#!/bin/bash

alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less

alias vim="nvim"
alias p="sudo pacman"
alias todo="python-todo"

alias gcl="git clone"
alias gc="git commit"
alias gp="git push"
alias gf="git fetch"
alias ga="git add"
alias gs="git status"
