#!/bin/bash

alias ls='ls --color=auto'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less

alias vim="nvim"
alias p="sudo pacman"
alias todo="python-todo"

alias gcl="git clone"
alias gc="git commit"
alias gp="git push"
alias gpu="git pull"
alias gf="git fetch"
alias ga="git add"
alias gs="git status"
alias gd="git diff"
alias gr="git revert"
alias gre="git reset"
