#!/bin/bash

alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less

alias vim="nvim"
alias p="sudo pacman"
alias todo="python-todo"
