#!/bin/bash

ping -q -c 1 8.8.8.8 > /dev/null 2>&1 || exit;

num_updates=$(yay -Qu | wc -l)

if [ $num_updates -eq "1" ]; then
	echo $num_updates update
else
	echo $num_updates updates
fi

# Notify user if they have a lot of updates (>= 50)
if [ $num_updates -ge "50" ]; then
	/usr/bin/notify-send "📦 You've got $num_updates updates!"
fi
