#!/bin/sh

# Generates zathura configuration file

. $HOME/.cache/wal/colors.sh

cat <<CONF
set default-bg "$background"
set default-fg "$foreground"

set tabbar-bg "$background"
set tabbar-fg "$foreground"

set tabbar-active-bg "$background"
set tabbar-active-fg "$foreground"

set recolor-darkcolor "$foreground"
set recolor-lightcolor "$background"

set statusbar-bg "$background"
set statusbar-fg "$foreground"

set inputbar-bg "$background"
set inputbar-fg "$foreground"

set completion-bg "$background"
set completion-fg "$foreground"

set completion-group-bg "$background"
set completion-group-fg "$color2"

set completion-highlight-bg "$background"
set completion-highlight-fg "$foreground"

set index-bg "$background"
set index-fg "$foreground"

set index-active-bg "$background"
set index-active-fg "$foreground"

set notification-bg "$background"
set notification-fg "$foreground"

set notification-error-bg "$color1"
set notification-error-fg "$foreground"

set notification-warning-bg "$color1"
set notification-warning-fg "$foreground"

set render-loading-bg "$background"
set render-loading-fg "$foreground"

set smooth-scroll true
set window-title-home-tilde true
set statusbar-basename true
set selection-clipboard clipboard

map r reload
map R rotate
CONF
