#!/bin/bash

# newsboat automatically reloads every 15 mins when opened
if pgrep -x "newsboat" > /dev/null; then
    exit
fi

# Ping 8.8.8.8 once to determine if we're connected to the internet
ping -q -c 1 8.8.8.8 > /dev/null 2>&1 || exit;

/usr/bin/newsboat -x reload

echo "$(newsboat -x print-unread | grep -Eo "[0-9]+") new"
