#!/bin/bash

ping -q -c 1 8.8.8.8 > /dev/null 2>&1 || { echo "No Internet"; exit; }

town=$(curl --silent https://www.geoip-db.com/json/ | grep -Po '"city":"\K[^"]*')
output=$(curl -s wttr.in/$town?format\="%C%20%t" | sed -e "s/\b\(.\)/\u\1/g")

# There's a typo in the source -- if out of queries, a single-line cURL returns 'unknow error' instead of 'unknown error'. Fix once PR is merged
if [[ ${output,,} =~ error|500|504|unknow ]];
then
	echo "Weather Error"
else
	echo $output
fi
